let host = 'http://www.realtoraccess.com';
export default {
    GET_LISTING_INFO:host+'/portal/listing/info/',
    GET_CRUMBS:host+'/portal/get/crumbs/',
    COMMIT_EMAIL:host+'/portal/commit/email/',
    GET_AGENT_LISTING:host+'/portal/get/agent/of/listing/',
    GET_RECOMMEND:host+'/portal/get/rcmd/listings/',
    CITY_PRICE:host+'/portal/city/price/',
    GET_NEARBY:host+'/portal/get/nearby/',
    NEW_LISTINGS:host+'/portal/new/listings/'
}

/*
{
  "message": "请求成功!", 
  "code": "00", 
  "data": {
    "toilet": "",  //卫生间
    "bedroom": "", //卧室
    "tax": "0.0", //地税
    "imgs": [  //图片
      "http://www.realtoraccess.com/data/listings/f1436266_1.jpg"
    ], 
    "intro": "Great place to build a two-storey home in neighbourhood of new homes. Level, cleared and regular shaped lots in ready to build condition. Quiet location with easy access to Sumas Way, Hwy #1 & Mission.", //房屋描述
    "parking": "5257 sq.ft.", //土地面积
    "listingname": "3492 HAZELWOOD PLACE", //地址
    "lng": "-117.0975515", 
    "builddate": "", //建筑年代
    "visit": 3,  //浏览量
    "housetype": "Other", //房型类型
    "goodat": "", //便利设施
    "datadate": "2016-10-08 19:56:00", 
    "good": 0, 
    "listingid": "f1436266", 
    "intro_eng": "", 
    "price": "$259,000",  //价格
    "cityname": "abbotsford", //城市
    "corp": "Royal LePage Global Force Realty", //地产公司
    "basement": "",  //地下室
    "lat": "32.7266207", 
    "housestyle": "",  //房屋风格
    "areas": "0 sqft.", //室内面积
    "schoolid": "", 
    "url": "http://ivyliou.ourubertor.com/abbotsford.ubr/3492-hazelwood-place-mls-reg-f1436266?order=listing_price%2520DESC&mls_number=F1436266&action=filter&acronym=FVREB", 
    "warning": "The data relating to real estate on this web site comes in part from the MLS Reciprocity program of the Real Estate Board of Greater Vancouver or the Fraser Valley Real Estate Board. Real estate listings held by participating real estate firms are marked with the MLSR logo and detailed information about the listing includes the name of the listing agent. This representation is based in whole or part on data generated by the Real Estate Board of Greater Vancouver or the Fraser Valley Real Estate Board which assumes no responsibility for its accuracy. The materials contained on this page may not be reproduced without the express written consent of the Real Estate Board of Greater Vancouver or the Fraser Valley Real Estate Board.Copyright 2016 by the Real Estate Board of Greater Vancouver, Fraser Valley Real Estate Board, Chilliwack and District Real Estate Board, BC Northern Real Estate Board, and Kootenay Real Estate Board. All Rights Reserved.", 
    "postid": ""
  }
}




*/